[project]
name = "rocrate-tabular"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "rocrate>=0.11.0",
    "sqlite-utils>=3.37",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
